#spring.application.name=customer
#
#spring.threads.virtual.enabled=true
#server.port=9999

spring:
  application:
    name: customer
  threads:
    virtual:
      enabled: true
server:
  port: 8080

app:
  my-key: $2a$12$zVRZfDSug16tA4HmdsfQ0OiAohXLNeBYU7QdgVDkrx.lSmceMWDxu
